version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/meeting/ # 프로젝트 이름
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: root
    - location: scripts/health_check.sh
      timeout: 180
      runas: root
    - location: scripts/switch.sh
      timeout: 180
      runas: root

