spring:
  datasource:
    url: jdbc:mysql://meeting-project-db.cyhjebvegioo.ap-northeast-2.rds.amazonaws.com:3306/meetingprojcet
    username: rladnjswnd96
    password: 306401jh
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect